Repository loolabs/waterpark, pull requests merged in 2021-02, with the labels that each got.

#30 💻 Implement fuzzy search
  client/components/ClubCard.tsx
  client/package.json
  client/pages/ClubList.tsx
  client/yarn.lock
Labels: frontend

#39 🗄 Restructure controllers/usecases
  server/src/modules/users/application/use-cases/create-user/create-user-controller.ts
  server/src/modules/users/application/use-cases/create-user/create-user-use-case.ts
  server/src/shared/app/base-controller.ts
  server/src/shared/app/controller-with-dto.ts
  server/src/shared/app/controller-without-dto.ts
  server/src/shared/app/typed-controller.ts
  server/src/shared/app/use-case-controller.ts
  server/src/shared/app/use-case-with-dto.ts
  server/src/shared/app/use-case-without-dto.ts
Labels: backend

#33 🗄 Get all clubs endpoint
  server/.dockerignore
  server/src/index.ts
  server/src/migrations/Migration20210123215506.ts
  server/src/modules/clubs/application/use-cases/get-all-clubs/__tests__/get-all-clubs-controller.test.unit.ts
  server/src/modules/clubs/application/use-cases/get-all-clubs/__tests__/get-all-clubs-use-case.test.unit.ts
  server/src/modules/clubs/application/use-cases/get-all-clubs/get-all-clubs-controller.ts
  server/src/modules/clubs/application/use-cases/get-all-clubs/get-all-clubs-use-case.ts
  server/src/modules/clubs/application/use-cases/get-all-clubs/index.ts
  server/src/modules/clubs/application/use-cases/get-all-clubs/test-utils/build-controller.ts
  server/src/modules/clubs/application/use-cases/get-all-clubs/test-utils/create-club-dtos.ts
  server/src/modules/clubs/application/use-cases/get-all-clubs/test-utils/create-clubs.ts
  server/src/modules/clubs/domain/entities/__tests__/club.test.unit.ts
  server/src/modules/clubs/domain/entities/club.ts
  server/src/modules/clubs/domain/events/club-created.ts
  server/src/modules/clubs/domain/value-objects/clubId.ts
  server/src/modules/clubs/infra/http/routes/index.ts
  server/src/modules/clubs/infra/repos/club-repo.ts
  server/src/modules/clubs/infra/repos/implementations/mikro-club-repo.ts
  server/src/modules/clubs/infra/repos/index.ts
  server/src/modules/clubs/mappers/club-dto.ts
  server/src/modules/clubs/mappers/club-map.ts
  server/src/modules/users/domain/entities/__tests__/user.test.unit.ts
  server/src/modules/users/domain/value-objects/user-password.ts
  server/src/shared/domain/aggregate-root.ts
  server/src/shared/infra/db/entities/club.entity.ts
  server/src/shared/infra/db/index.ts
  server/src/shared/infra/http/routes/index.ts
  server/yarn.lock
Labels: backend

#34 💻 Setup client side testing
  .prettierrc
  client/.babelrc
  client/__tests__/ClubList.test.tsx
  client/config/jest/cssTransform.js
  client/jest.config.js
  client/package.json
  client/pages/_app.tsx
  client/setupTests.js
  client/tsconfig.json
  client/utils/tests/test-utils.tsx
  client/yarn.lock
Labels: frontend

#38 🌎 Switch to npm with workspaces
  .github/workflows/test.yml
  .gitignore
  README.md
  client/package.json
  client/yarn.lock
  package-lock.json
  package.json
  server/.gitignore
  server/Dockerfile
  server/package.json
  server/src/index.ts
Labels: infra

#37 💻 Rerouting app & adding events list page and events detail page
  client/__tests__/ClubList.test.tsx
  client/components/ClubCard.tsx
  client/components/clubs/ClubCard.tsx
  client/components/clubs/ClubList.tsx
  client/components/clubs/index.ts
  client/components/events/EventCard.tsx
  client/components/events/EventList.tsx
  client/components/events/index.ts
  client/components/hooks/UseSearch.tsx
  client/components/hooks/index.ts
  client/components/index.ts
  client/pages/ClubList.tsx
  client/pages/_app.tsx
  client/pages/clubs/index.tsx
  client/pages/events/[id].tsx
  client/pages/events/index.tsx
  client/pages/index.tsx
  client/styles/ClubCard.module.css
  client/utils/tests/test-utils.tsx
Labels: frontend
